#!/bin/sh

set -e

modprobe openvswitch || true

echo "kernel modules loaded: "
# Check that ovs loaded
lsmod | grep "openvswitch"
echo "OK"

echo "Checking daemons: "
pgrep ovs-vswitchd
pgrep ovsdb-server
echo "OK"

echo -n "running openflow tests using mininet"
python `dirname $0`/openflow.py 2>&1
echo "OK"
