attributes:
    use_dpdk:
      type: "checkbox"
      weight: 20
      value: false
      label: "Use dpdk"
    use_dppd:
      type: "checkbox"
      weight: 20
      value: false
      label: "Use dppd"
