attributes:
    install_dpdk:
      type: "checkbox"
      weight: 20
      value: false
      label: "Install DPDK"
    install_nsh:
      type: "checkbox"
      weight: 20
      value: false
      label: "Install NSH"
    install_on_controller:
      type: "checkbox"
      weight: 20
      value: false
      label: "Install same OVS version on the Controller"
