etc/bash_completion.d/ovs-appctl-bashcomp.bash usr/share/bash-completion/completions
usr/bin/ovs-appctl
usr/bin/ovs-docker
usr/bin/ovs-ofctl
usr/bin/ovs-parse-backtrace
usr/bin/ovs-pki
usr/bin/ovsdb-client
usr/sbin/ovs-bugtool
usr/share/man/man1/ovsdb-client.1
usr/share/man/man1/ovsdb-tool.1
usr/share/man/man8/ovs-appctl.8
usr/share/man/man8/ovs-bugtool.8
usr/share/man/man8/ovs-ofctl.8
usr/share/man/man8/ovs-parse-backtrace.8
usr/share/man/man8/ovs-pki.8
usr/share/openvswitch/bugtool-plugins
usr/share/openvswitch/scripts/ovs-bugtool-*
usr/share/openvswitch/scripts/ovs-lib
